### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by RibusDesigns** [peter765/pineapple#2]
kevin@raspberrypi:\~/pineapple $ python3 bot.py
Starting Pineapple
Starting Discord Client
Loading plugins
Loaded plugin: PostImages.py
Loaded plugin: Poll.py
Loaded plugin: Waifu2x.py
Loaded plugin: Race.py
Loaded plugin: rate.py
Loaded plugin: ServerStats.py
Loaded plugin: Ship.py
Loaded plugin: JoinLeave.py
Loaded plugin: Kaomoji.py
Loaded plugin: Purge.py
Loaded plugin: osu.py
Traceback (most recent call last):
  File "bot.py", line 14, in <module>
    pm.load_plugins()
  File "/home/kevin/pineapple/PluginManager.py", line 56, in load_plugins
    spec.loader.exec_module(plugin)
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/kevin/pineapple/plugins/TrelloFeedback.py", line 2, in <module>
    from trello import trelloclient
  File "/usr/local/lib/python3.5/site-packages/trello/__init__.py", line 1, in <module>
    from urllib import quote_plus
ImportError: cannot import name 'quote_plus'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75e941d0>kevin@raspberrypi:~/pineapple $

**Comment by carloslubbers** [comment]
What python3 version are you using exactly?

**Comment by RibusDesigns** [comment]
3.5.2

**Comment by carloslubbers** [comment]
Hmm, seems to be something in the trello lib I'm using. What version of py-trello do you have (pip show py-trello)? If you want, you can safely delete TrelloFeedback.py from your plugins folder.

**Comment by Theraga** [comment]
This is probably because you installed trello instead of py-trello. Try to do "pip install py-trello" and remove trello with "pip uninstall trello" and see if that works.

**Comment by RibusDesigns** [comment]
That was it, thanks!
