### ISSUE TITLE
Ship error?

### ISSUE THREAD

**Issue by RibusDesigns** [peter765/pineapple#3]
Error: cannot identify image file 'cache/avatar/7235308da1718f20549b351bfe60be9d.png'

**Comment by RibusDesigns** [comment]
This is the whole traceback if it helps: 
Traceback (most recent call last):
  File "bot.py", line 42, in on_message
    await pm.handle_command(message, words[0][len(pm.botPreferences.commandPrefix):], words[1:])
  File "/home/kevin/RibusBot/PluginManager.py", line 82, in handle_command
    await target.handle_command(message_object, command, args)
  File "/home/kevin/RibusBot/plugins/Ship.py", line 31, in handle_command
    await self.ship(message_object)
  File "/home/kevin/RibusBot/plugins/Ship.py", line 77, in ship
    images = [Image.open(user1_img).resize((256, 256)), Image.open('images/ship/ship.png'),
  File "/usr/local/lib/python3.5/site-packages/PIL/Image.py", line 2349, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'cache/avatar/7235308da1718f20549b351bfe60be9d.png'

**Comment by carloslubbers** [comment]
Can you verify that the folder cache/avatar/ is present in the bot folder?  If not try to create it yourself. Also make sure the bot has sufficient permissions to write to that folder

**Comment by RibusDesigns** [comment]
This is a dumb question, but: How would I let the bot have sufficient permissions? Would running on root or using sudo help? Sorry, but I'm new to Linux and Raspberry Pi. And other stuff.

**Comment by carloslubbers** [comment]
Running as root might help, also make sure the raspberry has enough free space to cache the image files

**Comment by RibusDesigns** [comment]
Thanks
